services:
  - type: web
    name: wonderful-editor
    env: ruby
    buildCommand: |
      nvm install 20.18.0
      nvm use 20.18.0
      node -v
      yarn install --ignore-engines
      bundle install
      bundle exec rails assets:precompile
    startCommand: bundle exec rails server -b 0.0.0.0
