default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # ENV.fetch を使って、環境変数があればそれを、なければ "root" を使うようにします
  username: <%= ENV.fetch("POSTGRES_USER") { "root" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "root" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>

development:
  <<: *default
  database: wonderful_editor_development

test:
  <<: *default
  database: wonderful_editor_test

production:
  <<: *default
  database: wonderful_editor_production
  password: <%= ENV['WONDERFUL-EDITOR_DATABASE_PASSWORD'] %>
